### ISSUE TITLE
Understanding how to launch jobs to a queue from Python

### ISSUE THREAD

**Issue by jakirkham** [materialsproject/fireworks#111]
Up to this point, I have been able to nicely interact with code in iPython by constructing the tasks and establishing their dependencies. Finally, I launch them and can inspect the results.

Now, that I am moving to using a Sun Grid Engine queue I am little confused as to how I can do this. The documentation discuss how to do this with YAML files. However, I like the interactivity afford me by iPython and would like to continue writing code in Python.

I see that there is a `rapidfire` function for the queue, but I am unclear on how to get this to work. In particular, how can I set up the `CommonAdapter` so that it will launch this job in Python without going through a yaml file directly.

**Comment by computron** [comment]
Could you submit this issue to the dev list?

https://groups.google.com/forum/#!forum/fireworkflows

Note - I am flying today and busy most of tomorrow, so please excuse delays in responding.

Briefly, the two ways are:
i) Set up a my_qadapter.yaml file as in the tutorials, but configure things so that file is automatically read by FWS each time you start the system by setting an environment variable.
ii) Work purely in Python and feed in the appropriate "qadapter" object to the rapidfire() function of queue_launcher.py

I can provide more details on the dev list
