### ISSUE TITLE
PyTask won't return FWActions

### ISSUE THREAD

**Issue by zulissi** [materialsproject/fireworks#112]
Looking at the documentation for PyTask (https://pythonhosted.org/FireWorks/pytask.html), it looks like it's intended that it should be able to return a FWAction for message-passing etc, but I've been unable to make this work.   Looking at script_task.py it looks like it will never return the output.

Inserting something like
        elif isinstance(output,FWAction):
            return output
at the end of the PyTask definition makes it function as I understand it should.  

Am I missing something in how I should be using this?

**Comment by shyuep** [comment]
You need to supply a stored_data_varname in order for PyTask to return that output. 


Shyue Ping

On July 12, 2015 at 19:34:58, zulissi (notifications@github.com) wrote:

Looking at the documentation for PyTask (https://pythonhosted.org/FireWorks/pytask.html), it looks like it's intended that it should be able to return a FWAction for message-passing etc, but I've been unable to make this work. Looking at script_task.py it looks like it will never return the output.

Inserting something like
elif isinstance(output,FWAction):
return output
at the end of the PyTask definition makes it function as I understand it should.

Am I missing something in how I should be using this?

**Comment by zulissi** [comment]
But then it the output will get wrapped into a FWAction to update stored_data, without allowing for anything more dynamic.

"That function can (optionally) return a FWAction to perform dynamic actions "  - doesn't this imply that the function called by PyTask can return a custom FWAction that will get passed on?

**Comment by shyuep** [comment]
No it returns an FWACtion that updates stored data only. But that is already sufficient to do almost anything. E.g., the update can be to store the output in some variable name, and the next Task can use that stored data to do whatever custom action you require, including returning a customized FWAction.

**Comment by computron** [comment]
I agree with the OP - people should be able to return a custom FWAction via PyTask. The suggestion is reasonable - if the user returns a FWAction in their function, to go ahead and return that FWAction rather than return force the returned object to go into stored_data. I am going to make this change and push it out.

**Comment by computron** [comment]
Ok, this should be implemented in v1.08

**Comment by shyuep** [comment]
I am not sure what the fundamental objection here is. None of the current tasks return a custom FWAction. ScriptTask certainly just returns a stored data FWAction. same for the rest of the other tasks. Why is PyTask so special that it has to be the only task that supports a custom FWAction, when anything that is necessary can easily be handled via chaining of tasks? It seems to me an exercise in introducing unnecessary complexity.

**Comment by computron** [comment]
Because PyTask is supposed to be more flexible than the other tasks, and allow users to do *anything*. ScriptTask doesn't allow users to return a FWAction because it doesn't even call a Python function and catch the return object, it just calls a script (e.g. BASH script) for which it is impossible to catch back a Python object. Even in this scenario, for which I can't catch back a Python object and is expected to be much less dynamic than PyTask, someone can use the ScriptTask to write or append to a "FWAction.json" file that gets interpreted as a dynamic action.

Opposite to your view, I find your suggestion to "chain tasks" as an "exercise in introducing unnecessary complexity". Why should a user need to create an extra FireWork simply to query the DB for the stored value of the previous one and *return that again* to the next one? Is that how you would want your workflows to operate? It's certainly not something that I would ever want to have to do. Being able to return a FWAction in PyTask is completely reasonable and possible, it just makes PyTask much more attractive vs the alternative of writing your own FireTask via the API.

**Comment by shyuep** [comment]
Writing a func that returns a FWAction, and then using PyTask to call that function does not make sense to me. If you are going to implement that function, what’s preventing you from writing an actual FWTask returning that FWAction in the first place? The overhead is minimal, and you can do much more with that than using PyTask.

PyTask, though powerful, was never meant to supplant the writing of FWTasks. It is really meant for the execution of one liner Python functions. If someone really needs to handle complexity higher than just executing a one-liner python function and storing that output, he really should be writing a FWTask.

Anyway, since you already implemented it, I will just chalk this down to a difference in philosophy.
