### ISSUE TITLE
Launches

### ISSUE THREAD

**Issue by Kensuke-Hinata** [materialsproject/fireworks#166]
For the same firework id, there may be many different launches, how to trace the throwaway results in the workflow through the topological graph?

**Comment by computron** [comment]
Hi Pengyu

All the old launch data is retained in the "launches" collection of MongoDb; in the fireworks document, the older launch ids are put in the "archived_launches" key whereas the current launch is in the "launches" key.

You can view all launch data for a firework using "lpad get_fws -i <fw_id> -d all". There is also a corresponding function in the LaunchPad that will give you a Firework object along with all launch data. If you want to do anything more complicated you would need to write a custom Python function to query the data.

Best,
Anubhav

**Comment by Kensuke-Hinata** [comment]
I got it, what I feel confused is that one firework has a property "launches" with type list, does it mean that there may be many launches running at the same time for the firework?

**Comment by computron** [comment]
Hi Pengyu

In almost all instances, there should only be 1 launch in that field. The
exception to this is rare and involves duplicate checking with past jobs -
i.e., a current Firework might have duplicate matched to several historical
launches from different Fireworks that were all completed sucessfully, all
of which are considered to be valid launches of the current Firework. The
reason that the key is called "launches" is because in such situations
there could indeed be multiple valid launches for a Firework, and
historically in the first use case of Fireworks, this was a more major
concern and needed to be handled. For most users, I think it is OK to think
of launches as only have a single launch.

Best,
Anubhav

**Comment by Kensuke-Hinata** [comment]
OK, thanks a lot, I will continue to read the source code.
