### ISSUE TITLE
Recursion problem in Workflow.refresh method

### ISSUE THREAD

**Issue by gpetretto** [materialsproject/fireworks#180]
Hi,

I am having some problems with very large workflows due to the modifications in the refresh method in the Workflow class made some time ago (https://github.com/materialsproject/fireworks/commit/854816f1ab22da671ce64c5201dac5a1238c7508).
After the introduction of the defuse_workflow action the refresh is called on all the updated_ids and not only on the direct children, but consider this example workflow: one starting FW, with many children FWs depending on it (so that the dependencies are given by {fw1: [fw2, ...,fw100]}).
After the completion of fw1,  the FWs fw2-100 should be refreshed. However, when fw2 is refreshed this will still require to refresh again all the fw1-fw100 as well and so on. The refresh function is then called recursively several times. This leads in the best case to a considerable slow down of the refresh and potentially to a crash if the number of FWs is large enough (RuntimeError: maximum recursion depth exceeded. On my system this happens when the number of FWs is around 1000).
I suggest to change the method like this: https://github.com/gpetretto/fireworks/commit/4ac12b15307410477623a29dcd77e90e45542937
but, as I am not sure about the possible problematic cases related to the defuse_workflow option, could you please check if this modification will still properly cover all the other cases?

Thanks,

Guido

**Comment by computron** [comment]
Hi Guido,

Thanks for catching this issue. I am trying to work though the refresh() code since I am having some trouble retracing my own work. Here are my notes on the issue:

* When call Workflow.refresh(), the immediate thing to do is to refresh the state of the given fw_id. This might mean that the fw_id is going from "RESERVED" to "RUNNING" (e.g. if a launch has started running) or a fw_id is going from "WAITING" to "READY" (if all parents have completed) or "RUNNING" to "COMPLETED" (if the launch completed), etc. So far, so good since we are localizing the update to the fw_id that was actually specified by the user.
* If the state of the fw_id changed in any way, we also add it to "updated_ids". The updated_ids are returned back to the calling function. For example, the LaunchPad uses the list of of updated_ids when calling workflow.refresh() to know which entries to update in the database (rather than updating the entire Workflow).
* Next, if we ended up going to a COMPLETED state for that fw_id, there is code to apply the FWAction (whether it is to defuse the children, pass information to the children, detour around children, add new workflows, etc). Note that by applying this action, we will also change the information on the children. So, we need to add those children to the list of updated_ids so that the calling function knows they have been changed and can take appropriate action (e.g., re-insert the changed children information into the database)
* Finally, we want to call "refresh" on the children of the current fw_id. The only reason I can think to do this is that if the current fw_id is moved to COMPLETE or FIZZLED from its previous state. Then, the children might need to be refreshed from "WAITING" to "READY" (in the case of FIZZLED, only when "_allow_fizzled_parents" is on). I cannot think of another reason to refresh the children of the given fw_id other than this situation. e.g., even if a fw_id moves from READY to RUNNING or DEFUSED, or WAITING to READY, I don't see a reason for refreshing children.

So here are the two things I don't understand:
1. Why - even before "defuse_workflow" existed - is it necessary to refresh children unless the new state of the given fw_id is COMPLETED/FIZZLED.
2. Why - even if a whole bunch of fw_ids are now DEFUSED due to defuse_workflow - it is necessary to refresh them (i.e., refreshing all updated_ids).

Please let me know if you have any insight into points 1 and 2 that I am missing. The only thing I can think of is that, currently, "apply_action" might change the state of some Firework objects to be "DEFUSED" but it does not update the variable Workflow.fw_states to sync those changes. The latter was introduced by some others to speed up the operation of the FireWorks code, but it requires that the Workflow.fw_states variable is always kept in sync with the state of each Firework object. The refresh() call helps maintain this sync, and that is why refreshing *everything* that changed might have seemed necessary. But it might be possible to simply make sure that the Workflow.fw_states variable is updated properly in the apply_action() method.

I just tried implementing a much more "lightweight" refresh function based on the above conversation and pushed to master:

4267c0b819c6cdedcaa5d1ed64f16f271617ca80

Can you see if this solves your problem? Also please let me know if you foresee any issues or problms in my discussion as this is a major change in how refresh() works!

**Comment by computron** [comment]
Just a quick note - there are a few commits that pertain to this change, not just the latest one referenced above ... so if you are reviewing the changes please take a look at all the commits.

**Comment by gpetretto** [comment]
Hi Anubhav,

thanks for looking into that. 
I can't see any problem in your description of how refresh should work and I agree that the new implementation should be fine. This also solves my issue with the large workflow. However, I will keep thinking about it, in case I can imagine some weird scenario that is not taken into account by the new version. 
In this regard I may have an additional suggestion: what about adding a set of complicated test workflows (WFs with complicated topology, with several actions applied, with large number of FWs,...), in addition to the current test that instead focus on checking one functionality at a time? These may be excluded from the default test suite if they prove to be too time consuming and we can just start by adding workflows used to test reported issues. With time it should allow to cover a much larger variety of cases, helping to prevent regressions.

**Comment by computron** [comment]
Hi Guido

Happy to hear the revised code is working. I would like to add more tests to FWS, but unfortunately I just don't have the time to do it at the moment. Hopefully we can do this in the future. I am closing the issue for now, please let me know if you see any more problems.
