### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by shyuep** [materialsproject/fireworks#182]
Is there a reason why Flask and Flask-paginate and gunicorn needs to be a dependency of Fireworks? I understand that the web front end needs it, but if someone does not use the front end, these dependencies are not needed?

**Comment by computron** [comment]
Well before I respond in more detail - is it causing any specific problem for you? If yes, I can just separate it. If no we can do a philosophy discussion

**Comment by shyuep** [comment]
It increases the install size on some systems. Also, makes building packages more difficult. It is not a big deal, but I am wondering why the two needs to be bundled.

**Comment by computron** [comment]
The two don't need to be bundled, and when the frontend was in Django, I actually had them unbundled.

I felt Flask was pretty lightweight and didn't cause install problems. So rather than the "Linux" style of having everyone pick and choose what they want, I went with the "Apple" style of "once you pip install FireWorks, most people have everything they need". I also feel this encourages people to try typing "lpad webgui" (e.g. in the 5 minute tutorial) rather than create an additional barrier of having to install more things before trying to type that command. Note that some features like paramiko involve C compilation and I think can be more finicky, so I left those as extra options.

But if someone had trouble installing core FireWorks due to Flask, I would separate it out
