### ISSUE TITLE
pdb_on_exception - simpler + better way?

### ISSUE THREAD

**Issue by computron** [materialsproject/fireworks#255]
@montoyjh - regarding the ```pdb_on_exception``` functionality you added - does this library provide the same functionality without needing to add explicit options into the FWS source code (e.g., in rocket.py)?

http://boltons.readthedocs.io/en/latest/debugutils.html

**Comment by montoyjh** [comment]
As far as I can tell, the main tools only work for unhandled exceptions, so I don't think they'd be useful for simplifying the debugging functionality, because fireworks has a very well-defined general exception handling procedure within rocket.py.  Honestly, they don't really seem to add much to what the debugger already does.

wrap_trace seems like it could be pretty useful for profiling, etc, but it's not immediately clear to me how it could be used for what you're suggesting here.  I'll keep it in mind when I'm debugging to see if any ideas come to me for how this might be more generally useful in the future.

**Comment by computron** [comment]
Ah - the *unhandled* exception is what I missed. OK closing.
