### ISSUE TITLE
Add and remove firetasks from Fireworks

### ISSUE THREAD

**Issue by shyamd** [materialsproject/fireworks#295]
Add functions to add firetasks and remove firetasks for an already built firework.

**Comment by shyamd** [comment]
@computron I took a closer look at this and we may not actually need it. If you look at the code in atomate that injects in firetasks, it converts the firework to a dict, injects in the dict representation of firetask and then converts it back to a firework which suggests that adding and taking out firetasks is complicated.

When looking at the fireworks code, it looks like you can just add and remove firetask from fw.tasks and it should just work. I've made a suggestion to modify the docs in a PR

**Comment by computron** [comment]
I remember what happened now

About a year ago you could **not** just insert tasks this way. This is because the tasks got put inside the spec at object creation time.

I had modified the code about a year back to only put the tasks inside the spec at to_dict() time:
Commit: 6d2f2320405b50ecd0d5cec5e226d250da1e1b35

That made it possible to just modify tasks the way that you are saying. Although, as far as I remember we also changed the atomate powerups (that were earlier doing an ugly to_dict, modify, from_dict procedure) to use the more natural task insert procedure that you describe.

I agree it's good to have these in the docs
