### ISSUE TITLE
Problem with many detours

### ISSUE THREAD

**Issue by gpetretto** [materialsproject/fireworks#313]
I wanted to discuss about an issue connected to the maximum allowed size of the MongoDB document. 

If at some point in a workflow the generation of a large number of detours is needed, each with some specific input, the operation may fail with the error:
> pymongo.errors.DocumentTooLarge: command document too large. 

This is due to the fact that the whole `FWAction` (and thus all the detours with their inputs) is stored in the launch document.

Here is an example demonstrating the problem: https://gist.github.com/gpetretto/025d24c7a8f21c6ec40c6610b21424aa

One could avoid this kind of problem by generating the whole set of fireworks in the beginning, but this may not always be feasible and I have been asked to handle a case where each specific input is generated in the "parent" firework. 

Another workaround could be to save the inputs somewhere in the file system or in a database and let each child retrieve the required information. This does not seem so appealing, as it implies knowing beforehand whether this can happen or not and complicates the logic of the tasks.

So I would like to check if you would be interested in one of the following modifications (or any other) that would allow such a workflow to keep working irrespectively of the number of detours:
1) add an option in `fw_config` to completely disable the saving of the `FWAction` inside the launch document (or at least the `additions` and `detours` keys.)
2) remove the action from the launch if the size of the launch document exceeds the 16 MB limit:
```python
try:
    self.launches.find_one_and_replace({'launch_id': m_launch.launch_id},
                                       m_launch.to_db_dict(), upsert=True)
except DocumentTooLarge as e:
    # remove the action from the launch and try again
```
3) if the size of the launch document exceeds the 16 MB limit save the `FWAction` information to GridFS and store its id in place of the action in the launch document.

As a side note, of course the same problem will show up if a large number of fireworks try to update/mod the spec of a common child FW with a large enough amount of data. However this would not be solved so easily at the fireworks' level and seems easier to avoid with small modifications to the design of the wf.

Thanks

**Comment by computron** [comment]
Hi @gpetretto ,

Thanks very much for reporting this, for offering potential solutions as well as an offer to implement.

I think most users will probably prefer option 3. This will require no intervention from the user, retain all the information, and keep things working "normally" for most users.

You could have the name of the fallback GridFS collection be an option in the FWConfig (with some default value) if desired. If the user purposely sets this value to None/null, then the operation would essentially follow your second solution, i.e., the information is removed (perhaps instead of removing entirely, replace some string description like "5 FWS were added; information removed due to document size restrictions").

Would this work?
